language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
before_script:
  - npm install
  - npm test
script:
  - REACT_APP_TMDB_API_KEY=$TMDB_API_KEY npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_MDB_BUCKET
  region: eu-west-2
  skip_cleanup: true
  local-dir: build
before_deploy:
  - aws s3 rm s3://$S3_MDB_BUCKET --recursive