language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
before_script:
  - npm install
  - npm test
script:
  - REACT_APP_TMDB_API_KEY=$TMDB_API_KEY npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_MDB_BUCKET
  skip_cleanup: true
  local-dir: build
  acl: public_read
  cache_control: 'max-age=21600'